<?php
declare(strict_types=1);
require __DIR__.'/../backend/app.php';
function check(bool $ok,string $message): void { if (!$ok) throw new RuntimeException($message); echo "PASS $message\n"; }
function rejects(callable $fn,int $status,string $message): void { try { $fn(); } catch (ApiError $e) { check($e->status===$status,$message); return; } throw new RuntimeException('Expected rejection: '.$message); }
$c=['key'=>str_repeat('ab',32),'consent_version'=>'2026-10-06','rate_limit'=>2,'retention_days'=>90];
$db=new PDO(getenv('CM_TEST_DSN') ?: 'sqlite::memory:',getenv('CM_TEST_DB_USER') ?: null,getenv('CM_TEST_DB_PASSWORD') ?: null);$db->setAttribute(PDO::ATTR_ERRMODE,PDO::ERRMODE_EXCEPTION);
$db->exec('CREATE TABLE orders (id VARCHAR(36) PRIMARY KEY, fingerprint VARCHAR(64) NOT NULL, created_at BIGINT NOT NULL, payload MEDIUMTEXT NOT NULL, mail_status VARCHAR(16) NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, next_attempt BIGINT NOT NULL, lease VARCHAR(64) NULL, lease_until BIGINT NOT NULL DEFAULT 0)');
$app=new Orders($c,$db);
$p=json_decode(file_get_contents(__DIR__.'/../backend/catalog.json'),true)[0];
$d=['requestId'=>'11111111-1111-4111-8111-111111111111','name'=>'Тест','contact'=>'test@example.ru','comment'=>'Тестовая заявка','website'=>'','consent'=>true,'consentVersion'=>'2026-10-06','items'=>[['id'=>$p['id'],'quantity'=>2,'price'=>1]]];
$legacyId='00000000-0000-4000-8000-000000000001';$legacyCreated=strtotime('2026-10-06 21:30:00 UTC');
$legacyPayload=['name'=>$d['name'],'contact'=>$d['contact'],'comment'=>$d['comment'],'items'=>[['id'=>$p['id'],'sku'=>$p['sku'],'name'=>$p['name'],'brand'=>$p['brand'],'quantity'=>2,'price'=>$p['price']*2]],'total'=>$p['price']*2,'consentVersion'=>$c['consent_version'],'consent'=>['given'=>true,'at'=>'2026-10-06T20:30:00+00:00','version'=>$c['consent_version'],'sha256'=>hash('sha256','legacy consent'),'document'=>'legacy consent']];
$encrypt=new ReflectionMethod(Orders::class,'encrypt');$encrypted=$encrypt->invoke($app,$legacyPayload);$legacyInsert=$db->prepare("INSERT INTO orders (id,fingerprint,created_at,payload,mail_status,next_attempt) VALUES (?,?,?,?,'sent',?)");$legacyInsert->execute([$legacyId,'legacy',$legacyCreated,$encrypted,$legacyCreated]);
$app->migrate();$app->migrate();check(count($app->listing())===1 && $app->listing()[0]['order_number']===null && $app->listing()[0]['reference']==='Старая заявка от 07.10.2026','migration preserves unnumbered legacy listing and repeats safely');
$legacyRequest=array_replace($d,['requestId'=>$legacyId]);$legacyReplay=$app->accept($legacyRequest,'127.0.0.1','legacy consent');$legacyMail=$app->mailMessage($legacyId,$legacyPayload);check($legacyReplay['orderNumber']===null && $legacyReplay['createdAt']===$legacyCreated && $app->mailContent($legacyId)['label']==='Старая заявка от 07.10.2026' && str_contains($legacyMail['body'],'Старая заявка от 07.10.2026') && !str_contains($legacyMail['body'],$legacyId),'legacy replay and rendered mail keep stored Moscow date and human reference');
rejects(fn()=>$app->accept(array_replace($d,['consent'=>false]),'127.0.0.1','consent'),400,'consent required');
rejects(fn()=>$app->accept(array_replace($d,['consentVersion'=>'old']),'127.0.0.1','consent'),400,'consent version required');
rejects(fn()=>$app->accept(array_replace($d,['contact'=>"a@example.ru\r\nBcc: x@example.ru"]),'127.0.0.1','consent'),400,'header injection rejected');
rejects(fn()=>$app->accept(array_replace($d,['website'=>'bot']),'127.0.0.1','consent'),400,'honeypot rejected');
rejects(fn()=>$app->accept(array_replace($d,['items'=>[['id'=>'nonexistent','quantity'=>1]]]),'127.0.0.1','consent'),400,'unknown products rejected');
rejects(fn()=>$app->accept(array_replace($d,['items'=>[['id'=>$p['id'],'quantity'=>0]]]),'127.0.0.1','consent'),400,'invalid quantity rejected');
check($app->accept($d,'127.0.0.1','approved document')['ok'],'valid order stored');
$accepted=$app->accept($d,'127.0.0.1','approved document');check($accepted['orderNumber']===1 && $accepted['createdAt']>0,'first new persisted order receives number 1');
$payload=$app->export($d['requestId']);check($payload['total']===$p['price']*2,'server catalog sets price');
check($payload['consent']['sha256']===hash('sha256','approved document') && $payload['consent']['given'],'consent evidence persisted');
check(!str_contains($db->query('SELECT payload FROM orders')->fetchColumn(),'test@example.ru'),'PII encrypted in database');
$dRow=$db->prepare('SELECT order_number,created_at FROM orders WHERE id=?');$dRow->execute([$d['requestId']]);$storedOrder=$dRow->fetch(PDO::FETCH_ASSOC);check($accepted['orderNumber']===1 && $accepted['createdAt']===(int)$storedOrder['created_at'],'retry idempotent with stable number and date');
$mail=$app->mailMessage($d['requestId'],$payload);check(str_contains($mail['subject'],'Заявка № 1 от ') && str_contains($mail['body'],'Заявка № 1 от ') && !str_contains($mail['body'],$d['requestId']),'mail content includes assigned number/date without exposing internal UUID or sending');
$legacyCore=['name'=>$payload['name'],'contact'=>$payload['contact'],'comment'=>$payload['comment'],'items'=>$payload['items'],'total'=>$payload['total'],'consentVersion'=>$payload['consentVersion']];
$legacyFingerprint=hash_hmac('sha256',json_encode($legacyCore,JSON_UNESCAPED_UNICODE|JSON_THROW_ON_ERROR),hex2bin($c['key']));
$q=$db->prepare('UPDATE orders SET fingerprint=? WHERE id=?');$q->execute([$legacyFingerprint,$d['requestId']]);
$catalogProperty=new ReflectionProperty(Orders::class,'catalog');$catalog=$catalogProperty->getValue($app);
$changedCatalog=$catalog;$changedCatalog[$p['id']]['price']++;$changedCatalog[$p['id']]['name'].=' обновлённый';$catalogProperty->setValue($app,$changedCatalog);
check($app->accept($d,'127.0.0.1','approved document')['ok'] && count($app->listing())===2,'retry remains idempotent after catalog price and name change');
unset($changedCatalog[$p['id']]);$catalogProperty->setValue($app,$changedCatalog);
check($app->accept($d,'127.0.0.1','approved document')['ok'] && count($app->listing())===2,'retry remains idempotent after product removal');
$catalogProperty->setValue($app,$catalog);
rejects(fn()=>$app->accept(array_replace($d,['comment'=>'Changed']),'127.0.0.1','consent'),409,'id reuse with changed data rejected');
$d2=array_replace($d,['requestId'=>'22222222-2222-4222-8222-222222222222','items'=>[]]);$second=$app->accept($d2,'127.0.0.1','consent');check($second['ok'] && $second['orderNumber']===2,'global sequence increments across orders');
rejects(fn()=>$app->accept(array_replace($d,['requestId'=>'33333333-3333-4333-8333-333333333333']),'127.0.0.1','consent'),429,'persistent rate limit enforced');
$r=$app->deliver(function(){throw new RuntimeException('SMTP unavailable');});check($r['retry']===2 && count($app->listing())===3,'SMTP failure preserves orders');
$db->exec('UPDATE orders SET next_attempt=0');$sent=[];
$r=$app->deliver(function($id,$body)use(&$sent){$sent[]=$id;check(isset($body['contact']),'outbox decrypts mail content');});check($r['sent']===2,'outbox retries successfully');
check($app->deliver(fn()=>throw new RuntimeException('duplicate'))['sent']===0,'sent mail not resent');
check($app->delete($d2['requestId'])===1,'individual deletion');
$db->exec('UPDATE orders SET created_at=1');check($app->purge()===2 && !$app->listing(),'retention deletes payload and consent');
$app->migrate();$db->exec("CREATE TRIGGER reject_order BEFORE INSERT ON orders WHEN NEW.id='33333333-3333-4333-8333-333333333333' BEGIN SELECT RAISE(ABORT,'test rollback'); END");
try {$app->accept(array_replace($d,['requestId'=>'33333333-3333-4333-8333-333333333333']),'127.0.0.3','consent');throw new RuntimeException('Expected order insert rollback');} catch (ApiError $e) { check($e->status===409 && !$db->inTransaction(),'failed order insert rolls back through existing duplicate handler'); }
$db->exec('DROP TRIGGER reject_order');$next=$app->accept(array_replace($d,['requestId'=>'44444444-4444-4444-8444-444444444444']),'127.0.0.3','consent');check($next['orderNumber']===3,'rollback, purge, deletion, and repeat migration do not consume or reset sequence');
check(!Orders::configured([]),'unconfigured backend stays disabled');
echo "Backend checks complete\n";
